apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n3network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/n3br
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "n3br",
      "mtu": 1450,
      "ipam": {
        "type": "static"
      }
    }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n4network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/n4br
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "n4br",
      "mtu": 1450,
      "ipam": {
        "type": "static"
      }
    }'