apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
