apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open5gs

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: gnb-cm
    files:
      - config/open5gs-gnb.yaml
      - config/wrapper.sh