apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open5gs

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml

images:
  - name: gradiant/open5gs-webui
    newName: v2.7.5